server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        namespace: 6d3b0e7c-92e2-4aa8-8a96-22b4f26282a8

aliyun:
  oss:
 
